name: Notify Flask Server

on:
  push:
    branches: [ "main", "master" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook Payload to Flask
        run: |
          curl -X POST             -H "Content-Type: application/json"             -d '{"event": "push", "repo": "${{ github.repository }}", "actor": "${{ github.actor }}", "commit": "${{ github.sha }}"}'             http://yasserbdj96.hopto.org:5000/webhook
